trigger:
- main

resources:
  - repo: self

variables:
  dockerRegistryServiceConnection: 'a4f04d2d-a3e1-40ae-80aa-321005f23c28'
  containerRegistry: 'lthrecommendations.azurecr.io'

  imageRepositoryMain: 'lthrecommendations_main'
  dockerfileMain: '$(Build.SourcesDirectory)/Dockerfile.main'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

  lthproductionAppName: 'lthrecommendation'
  lthdevSlotName: 'lthrecommendation-dev'

  CLICKUP_API_KEY: $(CLICKUP_API_KEY)
  CLICKUP_LIST_ID: $(CLICKUP_LIST_ID)
  SCORES_FIELD_ID: $(SCORES_FIELD_ID)
  PLOT_FIELD_ID: $(PLOT_FIELD_ID)
  ANSWERS_FIELD_ID: $(ANSWERS_FIELD_ID)
  ROUTINES_FIELD_ID: $(ROUTINES_FIELD_ID)
  ACTIONPLAN_FIELD_ID: $(ACTIONPLAN_FIELD_ID)
  TYPEFORM_API_KEY: $(TYPEFORM_API_KEY)
  STRAPI_API_KEY: $(STRAPI_API_KEY)
  STRAPI_API_KEY_DEV: $(STRAPI_API_KEY_DEV)
  FORM_ID: $(FORM_ID)
  LINK_SUMMARY_TITLE_FIELD_ID: $(LINK_SUMMARY_TITLE_FIELD_ID)
  LINK_SUMMARY_SUMMARY_FIELD_ID: $(LINK_SUMMARY_SUMMARY_FIELD_ID)
  LINK_SUMMARY_OPENAI_API_KEY: $(LINK_SUMMARY_OPENAI_API_KEY)
  AZURE_BLOB_CONNECTION_STRING: $(AZURE_BLOB_CONNECTION_STRING)

stages:
- stage: Build
  displayName: Build and Push Stage
  jobs:
  - job: Build
    displayName: Build Docker Image
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    - task: Docker@2
      displayName: Build and push main_flask image
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepositoryMain)
        dockerfile: $(dockerfileMain)
        tags: |
          $(tag)
        buildContext: '$(Build.SourcesDirectory)'
        buildArguments: |
          CLICKUP_API_KEY=$(CLICKUP_API_KEY)
          CLICKUP_LIST_ID=$(CLICKUP_LIST_ID)
          SCORES_FIELD_ID=$(SCORES_FIELD_ID)
          PLOT_FIELD_ID=$(PLOT_FIELD_ID)
          ANSWERS_FIELD_ID=$(ANSWERS_FIELD_ID)
          ROUTINES_FIELD_ID=$(ROUTINES_FIELD_ID)
          ACTIONPLAN_FIELD_ID=$(ACTIONPLAN_FIELD_ID)
          TYPEFORM_API_KEY=$(TYPEFORM_API_KEY)
          STRAPI_API_KEY=$(STRAPI_API_KEY)
          STRAPI_API_KEY_DEV=$(STRAPI_API_KEY_DEV)
          FORM_ID=$(FORM_ID)
          LINK_SUMMARY_TITLE_FIELD_ID=$(LINK_SUMMARY_TITLE_FIELD_ID)
          LINK_SUMMARY_SUMMARY_FIELD_ID=$(LINK_SUMMARY_SUMMARY_FIELD_ID)
          LINK_SUMMARY_OPENAI_API_KEY=$(LINK_SUMMARY_OPENAI_API_KEY)
          AZURE_BLOB_CONNECTION_STRING=$(AZURE_BLOB_CONNECTION_STRING)

- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build
  jobs:
  - job: DeployProduction
    displayName: Deploy to Production Slot
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy main_flask image to Production
      inputs:
        azureSubscription: '$(dockerRegistryServiceConnection)'
        appName: '$(lthproductionAppName)'
        containers: |
          $(containerRegistry)/$(imageRepositoryMain):$(tag)

  - job: DeployDev
    displayName: Deploy to Dev Slot
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy main_flask image to Dev Slot
      inputs:
        azureSubscription: '$(dockerRegistryServiceConnection)'
        appName: '$(lthproductionAppName)'
        slotName: '$(lthdevSlotName)'
        containers: |
          $(containerRegistry)/$(imageRepositoryMain):$(tag)
