# Dockerfile
FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app

ARG CLICKUP_API_KEY
ARG CLICKUP_LIST_ID
ARG SCORES_FIELD_ID
ARG PLOT_FIELD_ID
ARG ANSWERS_FIELD_ID
ARG ROUTINES_FIELD_ID
ARG TYPEFORM_API_KEY
ARG FORM_ID
ARG LINK_SUMMARY_TITLE_FIELD_ID
ARG LINK_SUMMARY_SUMMARY_FIELD_ID
ARG LINK_SUMMARY_OPENAI_API_KEY

ENV CLICKUP_API_KEY=$CLICKUP_API_KEY
ENV CLICKUP_LIST_ID=$CLICKUP_LIST_ID
ENV SCORES_FIELD_ID=$SCORES_FIELD_ID
ENV PLOT_FIELD_ID=$PLOT_FIELD_ID
ENV ANSWERS_FIELD_ID=$ANSWERS_FIELD_ID
ENV ROUTINES_FIELD_ID=$ROUTINES_FIELD_ID
ENV TYPEFORM_API_KEY=$TYPEFORM_API_KEY
ENV FORM_ID=$FORM_ID
ENV LINK_SUMMARY_TITLE_FIELD_ID=$LINK_SUMMARY_TITLE_FIELD_ID
ENV LINK_SUMMARY_SUMMARY_FIELD_ID=$LINK_SUMMARY_SUMMARY_FIELD_ID
ENV LINK_SUMMARY_OPENAI_API_KEY=$LINK_SUMMARY_OPENAI_API_KEY

COPY . .

EXPOSE 80

CMD ["python", "main_flask.py"]
