version: '3.8'

services:
  web:
    build: .
    ports:
      - "5003:5003"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=development
