# Dockerfile.pubmed
FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    gnupg \
    libnss3 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libxkbcommon0 \
    --no-install-recommends && \
    wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && apt-get install -y --no-install-recommends \
        google-chrome-stable \
    && rm -rf /var/lib/apt/lists/*

ENV BROWSER_PATH=/usr/bin/google-chrome
ENV CHROME_FLAGS="--no-sandbox --disable-dev-shm-usage --disable-gpu"

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ARG CLICKUP_API_KEY
ARG CLICKUP_LIST_ID
ARG SCORES_FIELD_ID
ARG PLOT_FIELD_ID
ARG ANSWERS_FIELD_ID
ARG ROUTINES_FIELD_ID
ARG ACTIONPLAN_FIELD_ID
ARG TYPEFORM_API_KEY
ARG STRAPI_API_KEY
ARG FORM_ID
ARG LINK_SUMMARY_TITLE_FIELD_ID
ARG LINK_SUMMARY_SUMMARY_FIELD_ID
ARG LINK_SUMMARY_OPENAI_API_KEY
ARG AZURE_BLOB_CONNECTION_STRING

ENV CLICKUP_API_KEY=$CLICKUP_API_KEY
ENV CLICKUP_LIST_ID=$CLICKUP_LIST_ID
ENV SCORES_FIELD_ID=$SCORES_FIELD_ID
ENV PLOT_FIELD_ID=$PLOT_FIELD_ID
ENV ANSWERS_FIELD_ID=$ANSWERS_FIELD_ID
ENV ROUTINES_FIELD_ID=$ROUTINES_FIELD_ID
ENV ACTIONPLAN_FIELD_ID=$ACTIONPLAN_FIELD_ID
ENV TYPEFORM_API_KEY=$TYPEFORM_API_KEY
ENV STRAPI_API_KEY=$STRAPI_API_KEY
ENV FORM_ID=$FORM_ID
ENV LINK_SUMMARY_TITLE_FIELD_ID=$LINK_SUMMARY_TITLE_FIELD_ID
ENV LINK_SUMMARY_SUMMARY_FIELD_ID=$LINK_SUMMARY_SUMMARY_FIELD_ID
ENV LINK_SUMMARY_OPENAI_API_KEY=$LINK_SUMMARY_OPENAI_API_KEY
ENV AZURE_BLOB_CONNECTION_STRING=$AZURE_BLOB_CONNECTION_STRING

EXPOSE 80

CMD ["python", "pubmed_scraper.py"]
