version: '3.8'

services:
  # Recommendation Service
  recommendation-service:
    build: .
    container_name: lth-recommendation-service
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PORT=5000
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # User Test Service (Typeform-ClickUp Integration)
  user-test-service:
    build:
      context: ./user-test-service
      dockerfile: Dockerfile
    container_name: lth-user-test-service
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - USER_TEST_SERVICE_PORT=5001
      - FLASK_DEBUG=false
    restart: on-failure:5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s