FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install minimal system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ARG CLICKUP_API_KEY
ARG CLICKUP_LIST_ID
ARG SCORES_FIELD_ID
ARG PLOT_FIELD_ID
ARG ANSWERS_FIELD_ID
ARG ROUTINES_FIELD_ID
ARG ACTIONPLAN_FIELD_ID
ARG TYPEFORM_API_KEY
ARG STRAPI_API_KEY
ARG STRAPI_API_KEY_DEV
ARG FORM_ID
ARG LINK_SUMMARY_TITLE_FIELD_ID
ARG LINK_SUMMARY_SUMMARY_FIELD_ID
ARG LINK_SUMMARY_OPENAI_API_KEY
ARG AZURE_BLOB_CONNECTION_STRING
ARG APP_ENV

ENV CLICKUP_API_KEY=$CLICKUP_API_KEY
ENV CLICKUP_LIST_ID=$CLICKUP_LIST_ID
ENV SCORES_FIELD_ID=$SCORES_FIELD_ID
ENV PLOT_FIELD_ID=$PLOT_FIELD_ID
ENV ACTIONPLAN_FIELD_ID=$ACTIONPLAN_FIELD_ID
ENV ANSWERS_FIELD_ID=$ANSWERS_FIELD_ID
ENV ROUTINES_FIELD_ID=$ROUTINES_FIELD_ID
ENV STRAPI_API_KEY=$STRAPI_API_KEY
ENV STRAPI_API_KEY_DEV=$STRAPI_API_KEY_DEV
ENV TYPEFORM_API_KEY=$TYPEFORM_API_KEY
ENV FORM_ID=$FORM_ID
ENV LINK_SUMMARY_TITLE_FIELD_ID=$LINK_SUMMARY_TITLE_FIELD_ID
ENV LINK_SUMMARY_SUMMARY_FIELD_ID=$LINK_SUMMARY_SUMMARY_FIELD_ID
ENV LINK_SUMMARY_OPENAI_API_KEY=$LINK_SUMMARY_OPENAI_API_KEY
ENV AZURE_BLOB_CONNECTION_STRING=$AZURE_BLOB_CONNECTION_STRING
ENV APP_ENV=${APP_ENV}

EXPOSE 5003

CMD ["gunicorn", "--bind", "0.0.0.0:5003", "--workers", "3", "src.app:app"]
