version: '3.8'

services:
  # Recommendation Service
  recommendation-service:
    build: .
    container_name: lth-recommendation-service
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=development
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # User Test Service (Typeform-ClickUp Integration)
  user-test-service:
    build:
      context: ./user-test-service
      dockerfile: Dockerfile
    container_name: lth-user-test-service
    ports:
      - "5001:5001"
    volumes:
      - ./user-test-service/src:/app/src
      - ./user-test-service/cache:/app/cache
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=development
      - USER_TEST_SERVICE_PORT=5001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
