name: Build and deploy container app to Azure Web App - lthrecommendation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: lthrecommendations.azurecr.io
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push container image to Azure Container Registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: lthrecommendations.azurecr.io/lthrecommendations:${{ github.sha }}
        file: ./Dockerfile
        build-args: |
          CLICKUP_API_KEY=${{ secrets.CLICKUP_API_KEY }}
          CLICKUP_LIST_ID=${{ secrets.CLICKUP_LIST_ID }}
          SCORES_FIELD_ID=${{ secrets.SCORES_FIELD_ID }}
          PLOT_FIELD_ID=${{ secrets.PLOT_FIELD_ID }}
          ANSWERS_FIELD_ID=${{ secrets.ANSWERS_FIELD_ID }}
          ROUTINES_FIELD_ID=${{ secrets.ROUTINES_FIELD_ID }}
          TYPEFORM_API_KEY=${{ secrets.TYPEFORM_API_KEY }}
          FORM_ID=${{ secrets.FORM_ID }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lthrecommendation'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'lthrecommendations.azurecr.io/lthrecommendations:${{ github.sha }}'
